baseURL: https://graldij.github.io/
languageCode: en-us
title: Jacopo Graldi
theme: ["PaperMod"]
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  assets:
    customCSS: ["css/custom.css"]
